"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {Clock,Eye,Sparkles,Upload,Users,Wallet} from "lucide-react";
import {StudioShell} from "@/components/navigation/StudioShell";
import {StudioMetric} from "@/components/studio/StudioMetric";
import {VideoThumbnail} from "@/components/video/VideoThumbnail";
import {getVideos} from "@/services/video-service";
import {Video} from "@/types";
export default function StudioPage(){const[videos,setVideos]=useState<Video[]>([]);useEffect(()=>{getVideos().then(setVideos).catch(()=>setVideos([]))},[]);return <StudioShell><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-2xl font-semibold">Good evening, Rugved</h1><p className="mt-1 text-sm text-muted-foreground">Here&apos;s how your content is performing.</p></div><Link href="/studio/upload" className="flex h-10 items-center gap-2 rounded-full bg-adless-cyan px-5 text-sm font-semibold text-black"><Upload className="h-4 w-4"/>Upload Video</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StudioMetric label="Total Views" value="12.4K" delta="+18% vs last 28 days" icon={Eye}/><StudioMetric label="Watch Time" value="438 hrs" delta="+9% vs last 28 days" icon={Clock}/><StudioMetric label="Subscribers" value="1,284" delta="+142 this month" icon={Users}/><StudioMetric label="AI Placement Impressions" value="3.8K" delta="+24% vs last 28 days" icon={Sparkles} accent/><StudioMetric label="Estimated Revenue" value="$—" delta="Available after publication" icon={Wallet}/></div><section className="mt-10"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold">Recent videos</h2><Link href="/studio/content" className="text-sm text-adless-cyan hover:underline">View all content</Link></div><div className="mt-4 divide-y divide-border overflow-hidden rounded-xl border border-border bg-surface">{videos.map(video=><Link key={video.id} href={`/studio/videos/${video.id}`} className="flex flex-wrap items-center gap-4 p-4 transition hover:bg-elevated"><div className="relative aspect-video w-32 shrink-0 overflow-hidden rounded-lg"><VideoThumbnail thumbnailUrl={video.thumbnailUrl} videoSrc={video.videoSrc} alt={video.title}/></div><div className="min-w-[12rem] flex-1"><p className="line-clamp-1 text-sm font-semibold">{video.title}</p><p className="mt-1 text-xs text-muted-foreground">Published {video.uploadedAt}</p></div><span className="rounded-md bg-adless-cyan/10 px-2.5 py-1 text-xs text-adless-cyan">{video.storagePath?"AI ready":"Published"}</span><div className="w-20 text-sm text-muted-foreground">{video.views}</div></Link>)}{!videos.length&&<p className="p-10 text-center text-sm text-muted-foreground">No videos yet.</p>}</div></section></StudioShell>}
