"use client";
import {useEffect,useState} from "react";
import {MousePointerClick,Play,ShoppingBag,Timer} from "lucide-react";
import {StudioShell} from "@/components/navigation/StudioShell";
import {getPlacementAnalyticsSummary} from "@/services/video-service";
import {PlacementAnalyticsSummary} from "@/types";
const empty:PlacementAnalyticsSummary={placementImpressions:0,ctaImpressions:0,ctaClicks:0,ctaDismissals:0,exposureCompletions:0,ctaCtr:0};
export default function PlacementsPage(){const[data,setData]=useState(empty),[connected,setConnected]=useState(true);useEffect(()=>{getPlacementAnalyticsSummary().then(setData).catch(()=>setConnected(false))},[]);const cards=[["Placement impressions",data.placementImpressions,Play],["CTA impressions",data.ctaImpressions,ShoppingBag],["CTA clicks",data.ctaClicks,MousePointerClick],["Exposure completed",data.exposureCompletions,Timer]] as const;return <StudioShell title="AI placements"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,Icon])=><section key={label} className="rounded-xl border border-border bg-surface p-5"><Icon className="h-5 w-5 text-adless-cyan"/><p className="mt-4 text-sm text-[#aaa]">{label}</p><p className="mt-1 text-2xl font-semibold">{value.toLocaleString()}</p></section>)}</div><section className="mt-6 rounded-xl border border-border bg-surface p-6"><h2 className="font-semibold">Shoppable placement performance</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><Metric label="CTA click-through rate" value={`${(data.ctaCtr*100).toFixed(1)}%`}/><Metric label="CTA dismissals" value={String(data.ctaDismissals)}/><Metric label="Completed exposure" value={String(data.exposureCompletions)}/></div>{!connected&&<p className="mt-5 text-sm text-amber-200">Metrics are temporarily unavailable. Viewer playback remains unaffected.</p>}{connected&&data.placementImpressions===0&&<p className="mt-5 rounded-lg bg-background p-4 text-sm text-[#888]">No placement events have been recorded yet. Metrics will appear after viewers encounter an approved placement.</p>}<p className="mt-5 text-xs text-[#777]">Placement intelligence powered by ClickHouse. Values shown here come from recorded events; missing data is displayed as zero.</p></section></StudioShell>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-background p-4"><p className="text-xs text-[#777]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>}
